export const ADD_ITEM = 'ADD_ITEM';
export const SET_FEED_ITEMS = 'SET_FEED_ITEMS';
export const ADD_MY_RECEIVING_ITEM = 'ADD_MY_RECEIVING_ITEM';
export const SET_MY_RECEIVING_ITEM = 'SET_MY_RECEIVING_ITEM';
export const SET_REFRESH_FEED = 'SET_REFRESH_FEED';
