require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
target 'SHARE' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  target 'SHARETests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SHARE-tvOS' do
  # Pods for SHARE-tvOS

  target 'SHARE-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
